name: kr_otp
description: "A customizable OTP input field with an optional numeric keypad for Flutter."
version: 1.0.14
homepage: https://github.com/karrarfalih/kr_otp
screenshots:
  - description: 'This is screenshot that shows the use of the package'
    path: example/screenshots/screen2.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_shakemywidget: ^1.0.5+1
  motion_toast: ^2.12.1
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
